#!/bin/bash
# Init
FILE="/tmp/out.$$"
GREP="/bin/grep"
#....
# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root (or with sudo)" 1>&2
   exit 1
fi

echo "Put snd_hda_intel in power saving mode"
echo 0 >/sys/module/snd_hda_intel/parameters/power_save
echo Wait 12 seconds
sleep 5

echo "

DO NOT PLAY ANY SOUND WITH OTHER APPS !

"
sleep 7
for i in `seq 1 20`;
do
echo "$i - Exit snd_hda_intel from power saving mode"
echo 10 >/sys/module/snd_hda_intel/parameters/power_save
waiting=`expr $i + 13` 
echo "Wait $waiting seconds"
sleep $waiting
aplay /usr/share/sounds/alsa/Front_Center.wav
done
